version: '2'

services:

  petclinic:
    image: quitequiet/petclinic
    ports:
      - "8080:8080"
    volumes:
      - ./petclinic/config/server.xml:/opt/tomcat/conf/server.xml
    networks:
      - elk

  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    command:
      - "-e"
      - "--strict.perms=false" #avoids the need to restrict permissions for filebeat.yml to root user only (600)
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # needed to persist filebeat tracking data :
      - filebeat_data:/usr/share/filebeat/data:rw
      # needed to access all docker logs (read only) :
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
      # needed to access additional informations about containers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - logstash

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:$ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  filebeat_data:
