filebeat.inputs:
- type: log
  # Used this when was sending logs directly to Elasticsearch as a full string
  # Had to uncomment When added logstash as the log aggregator into the picture
  
  # json.add_error_key: true
  # json.ignore_decoding_error: true
  # json.message_key: log
  # enabled: true
  # encoding: utf-8

  fields_under_root: true
  paths:
  # Location of all our Docker log files (mapped volume in docker-compose.yml)
    - '/usr/share/dockerlogs/data/*/*.log'
    
processors:
- add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5000"]

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging:
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 7
#  level: debug
